[workspace]
resolver = "2"
members = [
    "domain",
    "rules",
    "engine",
    "world",
    "ai",
    "persist",
    "pack",
    "app",
    "cli",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MPL-2.0"
publish = false

[workspace.dependencies]
domain = { path = "domain" }
rules = { path = "rules" }
engine = { path = "engine" }
world = { path = "world" }
ai = { path = "ai" }
persist = { path = "persist" }
pack = { path = "pack" }
app = { path = "app" }
rand_core = "0.6"
rand_pcg = "0.3"
clap = { version = "4", features = ["derive"] }

[profile.release]
opt-level = 3
lto = true
panic = "unwind"

[profile.dev]
opt-level = 1
